version: '3.7'

services:
    database:
        build: ./postgresql
        ports:
          - 5432:5432
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: usr
          POSTGRES_PASSWORD: pwd
        networks:
          - app-network
        
    backend:
        build: ./spring2
        restart: always
        networks:
          - app-network
        ports:
          - 8080:8080
        depends_on:
          - database

    httpd:
        build: ./http
        ports:
          - 8081:80
        networks:
          - app-network
        depends_on:
          - backend

networks:
    app-network:
      
