version: '3.7'

services:
    database:
        build: ./postgresql
        ports:
          - 5432:5432
        networks:
          - app-network
        
    backend:
        build: ./spring2
        networks:
          - app-network
        ports:
          - 8080:8080
        depends_on:
          - database

    httpd:
        build: ./http
        ports:
          - 8081:80
        networks:
          - app-network
        depends_on:
          - database
          - backend

networks:
    app-network:
      
